### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by dennisguse** [scubajorgen/FitReader#4]
Under which license is the code released?

**Comment by scubajorgen** [comment]
Hi Dennis, so far I did not bother about licenses. Because of more questions like this I probably should.
For now, I am thinking about a liberal license like Apache 2.0, but I have to read more about this and decide based on the implications.
How do you intend to use the code?
Regards,
Jörgen

**Comment by dennisguse** [comment]
https://github.com/OpenTracksApp/OpenTracks/issues/637

**Comment by dennisguse** [comment]
And the license is?
A commit LICENSE.MD would be great :)

**Comment by scubajorgen** [comment]
MIT :-)

**Comment by dennisguse** [comment]
Cool!
A license.md file would be great also!
